Profiles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from pages.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('pages/', include('pages.urls',
                           namespace='pages')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         'name=django.contrib.sitemaps.views.sitemap')
]

pages/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'pages'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

pages/templates/pages/post/comment.html
{% extends "pages/base.html" %}

{% block title %}Добавление комментария{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Ваш комментарий был добавлен.</h2>
    <p><a href="{{ post.get_absolute_url }}">Назад к посту</a></p>
  {% else %}
    {% include "pages/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

pages/templates/pages/post/detail.html
{% extends "pages/base.html" %}
{% load pages_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1 class="title-main"><a href="{% url "pages:post_list" %}">На главную страницу</a></h1>
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}
    <p>
    <a href="{% url "pages:post_share" post.id %}">Поделиться этим постом</a>
    </p>
    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Похожие посты отсутствуют
    {% endfor %}
 {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Комментарий {{ forloop.counter }} от {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>Комментариев пока нет.</p>
  {% endfor %}

Всего статья просмотрена {{ total_views }} раз

  {% include "pages/post/includes/comment_form.html" %}
{% endblock %}

pages/templates/pages/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

pages/templates/pages/post/list.html
{% extends "pages/base.html" %}
{% load pages_tags %}

{% block title %}
    IT DIGEST PROFILES
{% endblock %}

{% block content %}
  <h1 class="title-main">IT DIGEST</h1>
    {% if tag %}
        <h2>Посты с тегом {{ tag.name }}</h2>
    {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "pages:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}
        ,
        {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

pages/templates/pages/post/search.html
{% extends "pages/base.html" %}
{% load pages_tags %}

{% block content %}
  {% if query %}
    <h1>Статья содержит запрос "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>По вашему запросов результатов не найдено, пожалуйста уменьшите или измените ваш поисковый запрос.</p>
    {% endfor %}
    <p><a href="{% url "pages:post_search" %}">Искать снова</a></p>
  {% else %}
    <h1>Поиск по статьям</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Искать">
    </form>
  {% endif %}
{% endblock %}

pages/templates/pages/post/share.html
{% extends "pages/base.html" %}

{% block title %}
    Поделиться
{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Письмо успешно отправлено</h1>
    <p>
      Пост:
      <p>
      <strong>"{{ post.title }}"</strong>
      <p>
      был успешно отправлен получателю:
      <p>
      <strong>{{ form.cleaned_data.to }}.</strong>
    </p>
  {% else %}
    <h1>Поделитесь этим постом "{{ post.title }}" посредством e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Отправить этот пост по e-mail">
    </form>
  {% endif %}
{% endblock %}