Profiles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from pages.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('pages/', include('pages.urls',
                           namespace='pages')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         'name=django.contrib.sitemaps.views.sitemap')
]

pages/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'pages'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

pages/templates/pages/base.html
{% load pages_tags %}
{% load static %}
<!DOCTYPE html> <html>
<head>
<title>
    {% block title %}
    {% endblock %}
</title>
<link href="{% static "pages.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
<h2>Последние обновления</h2>
<p>На данный момент опубликовано статей - {% total_posts %}</p>
    <strong><a href="{% url 'pages:post_feed' %}">Подпишитесь на ленту RSS</a></strong>
<h3>Последние статьи:</h3>
    {% show_latest_posts  %}
<h3>Самые комментируемые статьи:</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>